services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: e_commerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d e_commerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/e_commerce?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]
