// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategories = `-- name: CreateCategories :one
INSERT INTO categories (
 name,
 icon
) VALUES (
  $1, $2 
)
RETURNING id, name, icon, updated_at, created_at
`

type CreateCategoriesParams struct {
	Name string      `json:"name"`
	Icon pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategories, arg.Name, arg.Icon)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategories = `-- name: DeleteCategories :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategories(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategories, id)
	return err
}

const getCategories = `-- name: GetCategories :one
SELECT id, name, icon, updated_at, created_at FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategories(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategories, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoriesForUpdate = `-- name: GetCategoriesForUpdate :one
SELECT id, name, icon, updated_at, created_at FROM categories
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetCategoriesForUpdate(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoriesForUpdate, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, icon, updated_at, created_at FROM categories
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategories = `-- name: UpdateCategories :one
UPDATE categories
 set name = $2,
 icon = $3
WHERE id = $1
RETURNING id, name, icon, updated_at, created_at
`

type UpdateCategoriesParams struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Icon pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateCategories(ctx context.Context, arg UpdateCategoriesParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategories, arg.ID, arg.Name, arg.Icon)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
