// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: color_varian.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createColorVarianProduct = `-- name: CreateColorVarianProduct :one
INSERT INTO color_varians (
 product_id,
 color,
 images
) VALUES (
  $1, $2 ,$3
)
RETURNING id, product_id, color, images, updated_at, created_at
`

type CreateColorVarianProductParams struct {
	ProductID int64       `json:"product_id"`
	Color     string      `json:"color"`
	Images    pgtype.Text `json:"images"`
}

func (q *Queries) CreateColorVarianProduct(ctx context.Context, arg CreateColorVarianProductParams) (ColorVarian, error) {
	row := q.db.QueryRow(ctx, createColorVarianProduct, arg.ProductID, arg.Color, arg.Images)
	var i ColorVarian
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Color,
		&i.Images,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteColorVarianProduct = `-- name: DeleteColorVarianProduct :exec
DELETE FROM color_varians
WHERE id = $1
`

func (q *Queries) DeleteColorVarianProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteColorVarianProduct, id)
	return err
}

const getColorVarianProduct = `-- name: GetColorVarianProduct :one
SELECT id, product_id, color, images, updated_at, created_at FROM color_varians
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetColorVarianProduct(ctx context.Context, id int64) (ColorVarian, error) {
	row := q.db.QueryRow(ctx, getColorVarianProduct, id)
	var i ColorVarian
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Color,
		&i.Images,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getColorVarianProductForUpdate = `-- name: GetColorVarianProductForUpdate :one
SELECT id, product_id, color, images, updated_at, created_at FROM color_varians
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetColorVarianProductForUpdate(ctx context.Context, id int64) (ColorVarian, error) {
	row := q.db.QueryRow(ctx, getColorVarianProductForUpdate, id)
	var i ColorVarian
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Color,
		&i.Images,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listColorVarianProduct = `-- name: ListColorVarianProduct :many
SELECT id, product_id, color, images, updated_at, created_at FROM color_varians
WHERE product_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListColorVarianProductParams struct {
	ProductID int64 `json:"product_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListColorVarianProduct(ctx context.Context, arg ListColorVarianProductParams) ([]ColorVarian, error) {
	rows, err := q.db.Query(ctx, listColorVarianProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ColorVarian{}
	for rows.Next() {
		var i ColorVarian
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Color,
			&i.Images,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColorVarianProduct = `-- name: UpdateColorVarianProduct :one
UPDATE color_varians
 set color = $2,
 images = $3
WHERE id = $1
RETURNING id, product_id, color, images, updated_at, created_at
`

type UpdateColorVarianProductParams struct {
	ID     int64       `json:"id"`
	Color  string      `json:"color"`
	Images pgtype.Text `json:"images"`
}

func (q *Queries) UpdateColorVarianProduct(ctx context.Context, arg UpdateColorVarianProductParams) (ColorVarian, error) {
	row := q.db.QueryRow(ctx, updateColorVarianProduct, arg.ID, arg.Color, arg.Images)
	var i ColorVarian
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Color,
		&i.Images,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
