// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateColorVarianProduct(ctx context.Context, arg CreateColorVarianProductParams) (ColorVarian, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateShipping(ctx context.Context, arg CreateShippingParams) (Shipping, error)
	CreateSizeVarianProduct(ctx context.Context, arg CreateSizeVarianProductParams) (SizeVarian, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, id int64) error
	DeleteCategories(ctx context.Context, id int64) error
	DeleteColorVarianProduct(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id string) error
	DeletePayment(ctx context.Context, id int64) error
	DeletePaymentMethod(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteShipping(ctx context.Context, id int64) error
	DeleteSizeVarianProduct(ctx context.Context, id int64) error
	DeleteTransaction(ctx context.Context, txID string) error
	DeleteUser(ctx context.Context, uid string) error
	GetAddress(ctx context.Context, id int64) (Address, error)
	GetAddressForUpdate(ctx context.Context, id int64) (Address, error)
	GetCategories(ctx context.Context, id int64) (Category, error)
	GetCategoriesForUpdate(ctx context.Context, id int64) (Category, error)
	GetColorVarianProduct(ctx context.Context, id int64) (GetColorVarianProductRow, error)
	GetColorVarianProductForUpdate(ctx context.Context, id int64) (ColorVarian, error)
	GetOrder(ctx context.Context, id string) (GetOrderRow, error)
	GetOrderForUpdate(ctx context.Context, id string) (Order, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetPaymentForUpdate(ctx context.Context, id int64) (Payment, error)
	GetPaymentMethod(ctx context.Context, id int64) (PaymentMethod, error)
	GetPaymentMethodForUpdate(ctx context.Context, id int64) (PaymentMethod, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductForUpdate(ctx context.Context, id int64) (Product, error)
	GetProductWithDetail(ctx context.Context, id int64) (GetProductWithDetailRow, error)
	GetShipping(ctx context.Context, id int64) (Shipping, error)
	GetShippingForUpdate(ctx context.Context, id int64) (Shipping, error)
	GetSizeVarianProduct(ctx context.Context, id int64) (SizeVarian, error)
	GetSizeVarianProductForUpdate(ctx context.Context, id int64) (SizeVarian, error)
	GetTransaction(ctx context.Context, txID string) (GetTransactionRow, error)
	GetTransactionForUpdate(ctx context.Context, txID string) (Transaction, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, uid string) (User, error)
	GetUserLogin(ctx context.Context, email string) (User, error)
	ListAddress(ctx context.Context, arg ListAddressParams) ([]Address, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListColorVarianProduct(ctx context.Context, arg ListColorVarianProductParams) ([]ListColorVarianProductRow, error)
	ListOrder(ctx context.Context, arg ListOrderParams) ([]ListOrderRow, error)
	ListPayment(ctx context.Context, arg ListPaymentParams) ([]Payment, error)
	ListPaymentMethod(ctx context.Context, arg ListPaymentMethodParams) ([]PaymentMethod, error)
	ListProduct(ctx context.Context, arg ListProductParams) ([]ListProductRow, error)
	ListShipping(ctx context.Context, arg ListShippingParams) ([]Shipping, error)
	ListSizeVarianProduct(ctx context.Context, arg ListSizeVarianProductParams) ([]SizeVarian, error)
	ListTransaction(ctx context.Context, arg ListTransactionParams) ([]ListTransactionRow, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateCategories(ctx context.Context, arg UpdateCategoriesParams) (Category, error)
	UpdateColorVarianProduct(ctx context.Context, arg UpdateColorVarianProductParams) (ColorVarian, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateShipping(ctx context.Context, arg UpdateShippingParams) (Shipping, error)
	UpdateSizeVarianProduct(ctx context.Context, arg UpdateSizeVarianProductParams) (SizeVarian, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
